[package]
name = "fire-sensor-example"
version = "0.1.0"
authors = ["Choi-Jungwoo <jungwoo@cineuse.com>"]
edition = "2018"

[dependencies]
xtensa-lx-rt = "0.5.0"
xtensa-lx = "0.3.0"
panic-halt = "0.2.0"

esp8266-hal = { version = "0.4.0", optional = true }
